apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{name}}-prod

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/{{name}}
    newTag: prod

patches:
  - path: replicas.yaml
    target: { kind: Deployment, name: {{name}} }
