using System.CommandLine;
using System.Diagnostics;
using Spectre.Console;

namespace DevStart.Commands;

/// <summary>
/// <c>dev-start promote &lt;env&gt;</c> — reads <c>.devstart.json</c> plus the
/// installed capability list, and writes an env-specific
/// <c>values.generated.yaml</c> into <c>k8s/overlays/&lt;env&gt;/</c>. Safe to
/// re-run; only touches <c>*.generated.yaml</c>.
/// </summary>
public static class PromoteCommand
{
    private static readonly HashSet<string> KnownEnvs = new(StringComparer.OrdinalIgnoreCase)
    {
        "dev", "stage", "prod",
    };

    public static Command Build()
    {
        var envArg = new Argument<string>("env", "Target environment (dev | stage | prod).");
        var projectOpt = new Option<string>(["--project", "-p"], () => ".", "Path to the target project.");
        var outputOpt = new Option<string?>("--output",
            "Override output directory (default: k8s/overlays/<env>).");
        var renderOpt = new Option<bool>("--render",
            "After writing values, shell out to `helm template` and write `rendered.yaml`. Requires helm on PATH.");

        var cmd = new Command("promote",
            "Emit env-specific Kubernetes values from the project manifest.")
        {
            envArg, projectOpt, outputOpt, renderOpt,
        };

        cmd.SetHandler((env, projectPath, output, render) =>
        {
            if (!KnownEnvs.Contains(env))
            {
                AnsiConsole.MarkupLine($"[red]Unknown env[/] '{env}'. Expected: dev | stage | prod.");
                Environment.ExitCode = 2;
                return;
            }

            var root = Path.GetFullPath(projectPath);
            var manifest = Manifest.Load(root);

            if (!manifest.Capabilities.Contains("k8s", StringComparer.Ordinal))
            {
                AnsiConsole.MarkupLine("[red]k8s capability not installed[/]. Run [cyan]dev-start add k8s[/] first.");
                Environment.ExitCode = 2;
                return;
            }

            var outDir = output is null
                ? Path.Join(root, "k8s", "overlays", env.ToLowerInvariant())
                : Path.GetFullPath(output);
            Directory.CreateDirectory(outDir);

            var values = BuildValues(env, manifest);
            var valuesPath = Path.Join(outDir, "values.generated.yaml");
            File.WriteAllText(valuesPath, values);

            AnsiConsole.MarkupLine($"[green]wrote[/] {Path.GetRelativePath(root, valuesPath)}");

            if (render)
            {
                var rendered = TryHelmTemplate(root, env);
                if (rendered is null)
                {
                    AnsiConsole.MarkupLine("[yellow]skip render[/] — helm not found on PATH.");
                }
                else
                {
                    var renderedPath = Path.Join(outDir, "rendered.yaml");
                    File.WriteAllText(renderedPath, rendered);
                    AnsiConsole.MarkupLine($"[green]wrote[/] {Path.GetRelativePath(root, renderedPath)}");
                }
            }
        }, envArg, projectOpt, outputOpt, renderOpt);

        return cmd;
    }

    internal static string BuildValues(string env, Manifest manifest)
    {
        var (replicas, cpu, mem, hpaEnabled) = env.ToLowerInvariant() switch
        {
            "dev" => (1, "50m", "128Mi", false),
            "stage" => (2, "100m", "256Mi", true),
            "prod" => (3, "200m", "512Mi", true),
            _ => (1, "100m", "256Mi", false),
        };

        var hasDb = manifest.Capabilities.Contains("postgres", StringComparer.Ordinal)
            || manifest.Capabilities.Contains("ts-postgres", StringComparer.Ordinal);
        var hasOtel = manifest.Capabilities.Contains("otel", StringComparer.Ordinal)
            || manifest.Capabilities.Contains("ts-otel", StringComparer.Ordinal);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"# generated by `dev-start promote {env}` — re-run to regenerate.");
        sb.AppendLine($"# project: {manifest.Name}  stack: {manifest.Stack}  env: {env}");
        sb.AppendLine();
        sb.AppendLine("image:");
        sb.AppendLine($"  tag: {env}");
        sb.AppendLine();
        sb.AppendLine($"replicaCount: {replicas}");
        sb.AppendLine();
        sb.AppendLine("resources:");
        sb.AppendLine($"  requests: {{ cpu: {cpu}, memory: {mem} }}");
        sb.AppendLine();
        sb.AppendLine("ingress:");
        sb.AppendLine("  enabled: true");
        sb.AppendLine($"  host: {manifest.Name}.{env}.example.com");
        sb.AppendLine();
        sb.AppendLine("hpa:");
        sb.AppendLine($"  enabled: {hpaEnabled.ToString().ToLowerInvariant()}");
        sb.AppendLine();
        sb.AppendLine("migrations:");
        sb.AppendLine($"  enabled: {hasDb.ToString().ToLowerInvariant()}");
        sb.AppendLine();
        sb.AppendLine("otel:");
        sb.AppendLine($"  enabled: {hasOtel.ToString().ToLowerInvariant()}");
        if (hasOtel)
        {
            sb.AppendLine("  endpoint: http://otel-collector.observability:4317");
        }
        sb.AppendLine();
        sb.AppendLine("services:");
        foreach (var s in manifest.Services) sb.AppendLine($"  - {s}");
        return sb.ToString();
    }

    private static string? TryHelmTemplate(string root, string env)
    {
        try
        {
            var chart = Path.Join(root, "k8s", "helm");
            var valuesShared = Path.Join(chart, "values.yaml");
            var valuesEnv = Path.Join(chart, $"values-{env}.yaml");
            var valuesGen = Path.Join(root, "k8s", "overlays", env, "values.generated.yaml");

            var args = new List<string> { "template", "--include-crds", chart };
            if (File.Exists(valuesShared)) { args.Add("-f"); args.Add(valuesShared); }
            if (File.Exists(valuesEnv)) { args.Add("-f"); args.Add(valuesEnv); }
            if (File.Exists(valuesGen)) { args.Add("-f"); args.Add(valuesGen); }

            var psi = new ProcessStartInfo("helm")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = root,
            };
            foreach (var a in args) psi.ArgumentList.Add(a);

            using var p = Process.Start(psi);
            if (p is null) return null;
            var stdout = p.StandardOutput.ReadToEnd();
            p.WaitForExit();
            return p.ExitCode == 0 ? stdout : null;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            return null;
        }
    }
}
