apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{name}}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Release.Namespace | quote }}
  DOTNET_RUNNING_IN_CONTAINER: "true"
