apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{name}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{name}}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{name}}
            {{- end }}
            {{- range .Values.env }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.service.targetPort }} }
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.service.targetPort }} }
